README.markdown
Fixed "org.java_websocket.server.WebSocketClient" to "org.java_websocket.client.WebSocketClient"
=> FIXED typo in README.markdown

src/main/java/org/java_websocket/SSLSocketChannel2.java
=> TooTallNate#171

src/main/java/org/java_websocket/WebSocket.java, src/main/java/org/java_websocket/WebSocketAdapter.java, src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/WebSocketListener.java, src/main/java/org/java_websocket/server/WebSocketServer.java, src/main/java/org/java_websocket/util/Base64.java
These error cause the Maven build not to complete.
=> Fixed Javadoc errors

src/main/java/org/java_websocket/server/WebSocketServer.java
=> Fix stop joining thread before interrupting Selector.select

src/main/java/org/java_websocket/WebSocketImpl.java
=> [Typo] Fixes typo in WebSocketImpl.java

.gitignore, .travis.yml, README.markdown
Including update for the Travis CI and remove of maven
=> Small changes to README 

src/main/java/org/java_websocket/client/WebSocketClient.java, src/main/java/org/java_websocket/drafts/Draft.java
=> Use URI encoding in request, fix typos

src/main/java/org/java_websocket/client/WebSocketClient.java
Getter to allow hostname verification for android
for #452
=> Added getter for the socket in WebSocketClient

src/main/example/ChatServer.java, src/main/java/org/java_websocket/client/WebSocketClient.java, src/main/java/org/java_websocket/drafts/Draft_10.java, src/main/java/org/java_websocket/server/WebSocketServer.java, src/test/java/org/java_websocket/AutobahnClientScenario.java, src/test/java/org/java_websocket/example/AutobahnServerTest.java
onStart is going to get called when server is successfully started
#271
=> Added callback for successfull start of server

src/main/java/org/java_websocket/client/WebSocketClient.java
WebSocketClient and writeThread cannot be garbage collected
=> Fix for #217 by ddrscott

src/main/java/org/java_websocket/server/WebSocketServer.java
Closing worker threads on IOException during bind
=> Fix for #222

src/main/example/ChatClient.java, src/main/example/ExampleClient.java, src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/drafts/Draft_10.java, src/main/java/org/java_websocket/drafts/Draft_75.java, src/main/java/org/java_websocket/drafts/Draft_76.java
=> Deprecating drafts

src/main/java/org/java_websocket/SSLSocketChannel.java, src/main/java/org/java_websocket/util/ByteBufferUtils.java
New SSLSocketChannel is available in the branch but not activly used
=> Recommit SSLSocketChannel

README.markdown
=> Link to javadocs

src/main/java/org/java_websocket/drafts/Draft.java
=> Append values if key already exists in handshake

build.xml, src/main/java/org/java_websocket/drafts/Draft_6455.java
=> Ant fails due to missing `dist/` directory

build.xml, src/main/java/org/java_websocket/client/WebSocketClient.java
Add support for proxy when using wss
=> Add proxy support for WSS

src/main/java/org/java_websocket/AbstractWebSocket.java, src/main/java/org/java_websocket/client/WebSocketClient.java, src/main/java/org/java_websocket/drafts/Draft_6455.java, src/main/java/org/java_websocket/framing/FramedataImpl1.java, src/main/java/org/java_websocket/server/WebSocketServer.java
#528
Cleaned up some debug printouts
=> Added setter for SO_REUSEADDR

src/main/java/org/java_websocket/drafts/Draft_6455.java, src/main/java/org/java_websocket/extensions/DefaultExtension.java, src/main/java/org/java_websocket/extensions/IExtension.java
When the draft will be reset, also the extension should be reset
=> Added reset method for extensions called by the draft

src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/drafts/Draft_6455.java
Implemented correct responses for handshake errors (see #530)
Removed possible Nullpointer in the toString() method
=> Responses to handshake errors

src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/WebSocketServerFactory.java, src/main/java/org/java_websocket/drafts/Draft_6455.java, src/main/java/org/java_websocket/server/WebSocketServer.java
Moved WebSocketServerFactory to seperate file
Changed the way how the last pong is updated
=> Code cleanups

src/main/java/org/java_websocket/server/DefaultSSLWebSocketServerFactory.java, src/main/java/org/java_websocket/server/DefaultWebSocketServerFactory.java
This is a build fix after 'merge pull request #541'.
=> build fix.

src/main/example/ChatServer.java, src/main/java/org/java_websocket/WebSocket.java, src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/client/WebSocketClient.java, src/main/java/org/java_websocket/drafts/Draft.java, src/main/java/org/java_websocket/drafts/Draft_10.java, src/main/java/org/java_websocket/drafts/Draft_6455.java, src/main/java/org/java_websocket/extensions/DefaultExtension.java, src/main/java/org/java_websocket/server/WebSocketServer.java
- broadcast method to send a text to a specific list of users (see #539)
- hashCode && equals override for drafts and extensions
- changed examples to new method broadcast
=> Implementation of a broadcast method

src/main/java/org/java_websocket/WebSocketImpl.java
Show info for broken pipe exception just in debug mode (see #545)
=> Ignore Broken pipe exception

src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/WebSocketListener.java, src/main/java/org/java_websocket/drafts/Draft_6455.java, src/main/java/org/java_websocket/server/WebSocketServer.java, src/test/java/org/java_websocket/example/AutobahnServerTest.java
This should fix #564 as well as other issues like that
=> Deprecating onFragment and combining fragmented frames

src/main/example/ExampleClient.java, src/main/java/org/java_websocket/drafts/Draft.java
=> InvalidHandshakeException on invalid status line

src/main/java/org/java_websocket/AbstractWebSocket.java
Calling the setter starts the timer, which may cause a
WebsocketNotConnectedException (see #579)
Using the setter to change the connection lost timeout started the timer which caused an exception
#579 
Removed start of timer in the setter and added a reset option, if timer or timertask is not null
Tested against simple project with no connection and timer interval set to 1 caused the error.
After the bug fix there is no error
=> Connection lost timer should not start on setter call

.gitignore, src/main/java/org/java_websocket/drafts/Draft.java
When a InvalidHandShakeException is thrown, the whole invalid status
line should be included
Included the whole status line which caused the error
#390 
The exception may not be clear enough without it
No test
=> Include whole invalid status line

src/test/java/org/java_websocket/extensions/AllExtensionTests.java, src/test/java/org/java_websocket/extensions/DefaultExtensionTest.java, src/test/java/org/java_websocket/issues/AllIssueTests.java, src/test/java/org/java_websocket/issues/Issue609Test.java, src/test/java/org/java_websocket/misc/OpeningHandshakeRejectionTest.java, src/test/java/org/java_websocket/protocols/ProtoclHandshakeRejectionTest.java, src/test/java/org/java_websocket/util/SocketUtil.java
Some more JUnit tests and setup for jenkins builds and tests
Improve quality of the product
=> Extended JUnit test

pom.xml, src/test/java/org/java_websocket/autobahn/AutobahnServerResults.java
Included a Autobahn testsuite evaluator for the jenkins job
Improve test coverage
=> Autobahn testsuite evaluation

src/main/java/org/java_websocket/client/WebSocketClient.java, src/test/java/org/java_websocket/autobahn/AutobahnServerResults.java
Additional javadocs
None
Improve quality
No need for test
=> Adjusted JUnit test and extended javadoc

src/main/example/SecWebSocketProtocolClientExample.java
Added example for Sec-WebSocket-Protocol
Fixes #618 
Examples help others how to use features
No tests needed
=> Added example for Sec-WebSocket-Protocol

README.markdown, src/main/example/ChatServer.java, src/main/example/ChatServerAttachmentExample.java, src/main/example/ExampleClient.java
Links to the examples in the README
Extended the examples
None
Make it easier for new people
No tests necessary.
=> Update Readme and examples

src/main/java/org/java_websocket/client/WebSocketClient.java, src/test/java/org/java_websocket/issues/Issue256Test.java
Reworked the test
More stable on jenkins
=> Reworked Reconnect test

src/main/example/CustomHeaderClientExample.java, src/main/example/ExampleClient.java, src/main/example/ServerRejectHandshakeExample.java, src/main/java/org/java_websocket/client/WebSocketClient.java
Added example for custom headers in the WebSocketClient
Fixes #490
Documentation
=> Added example for custom header

src/main/java/org/java_websocket/client/package-info.java, src/main/java/org/java_websocket/drafts/package-info.java, src/main/java/org/java_websocket/exceptions/package-info.java, src/main/java/org/java_websocket/extensions/package-info.java, src/main/java/org/java_websocket/framing/ControlFrame.java, src/main/java/org/java_websocket/framing/DataFrame.java, src/main/java/org/java_websocket/framing/Framedata.java, src/main/java/org/java_websocket/framing/FramedataImpl1.java, src/main/java/org/java_websocket/framing/package-info.java, src/main/java/org/java_websocket/handshake/ClientHandshake.java, src/main/java/org/java_websocket/handshake/ClientHandshakeBuilder.java, src/main/java/org/java_websocket/handshake/HandshakeBuilder.java, src/main/java/org/java_websocket/handshake/HandshakeImpl1Client.java, src/main/java/org/java_websocket/handshake/HandshakeImpl1Server.java, src/main/java/org/java_websocket/handshake/Handshakedata.java, src/main/java/org/java_websocket/handshake/HandshakedataImpl1.java, src/main/java/org/java_websocket/handshake/ServerHandshake.java, src/main/java/org/java_websocket/handshake/package-info.java, src/main/java/org/java_websocket/protocols/package-info.java, src/main/java/org/java_websocket/server/package-info.java, src/main/java/org/java_websocket/util/package-info.java
Extend javadocs
Documentation
No tests required
=> Extend JavaDoc coverage

src/main/example/ServerAdditionalHeaderExample.java
Additional example on how to add an additional http-header for the server response
Fixes #490
Improve documentation
No tests needed
=> Example on how to add additional header serverside

src/main/java/org/java_websocket/client/WebSocketClient.java, src/test/java/org/java_websocket/issues/Issue666Test.java
See #667
Fixes #666
See #667 
Adjusted test
=> Change thread name

README.markdown
=> Fixed minor typos

README.markdown
Just reference the example folder
None
Clearer readme
Not needed
=> Change example section

pom.xml, src/test/java/org/java_websocket/issues/Issue256Test.java
Make reconnect test not failing
Change pom
#729
Automatic snapshots
Local
=> Prepare for automatic snapshot deploy

README.markdown
Badge for Snapshots
Fixes #729 
Visibility
Manual test
=> Adjust readme

src/main/java/org/java_websocket/drafts/Draft_6455.java
=> Fixed typo in Draft_6455

README.markdown, pom.xml
=> Update to 1.3.9

src/test/java/org/java_websocket/issues/Issue713Test.java
Added tests for the broadcast methods (Basic ones)
Fixes #713 
More tests
=> Added tests for broadcast

src/main/java/org/java_websocket/server/WebSocketServer.java
close() should be called when the WebSocketServerFactory gets updated
Found with #765 
Bug
No test needed
=> Close WebSocketFactory when updated

src/test/java/org/java_websocket/issues/Issue256Test.java, src/test/java/org/java_websocket/issues/Issue580Test.java
Rework tests to use parameters when useful
Improve test
=> Uses parameters

src/main/java/org/java_websocket/AbstractWrappedByteChannel.java, src/main/java/org/java_websocket/WebSocketImpl.java, src/main/java/org/java_websocket/client/WebSocketClient.java, src/main/java/org/java_websocket/drafts/Draft.java, src/main/java/org/java_websocket/drafts/Draft_6455.java, src/main/java/org/java_websocket/framing/CloseFrame.java, src/main/java/org/java_websocket/server/WebSocketServer.java, src/test/java/org/java_websocket/protocols/ProtoclHandshakeRejectionTest.java, src/test/java/org/java_websocket/protocols/ProtocolTest.java
Reduced complexity
Removed found issues
Fixed wrong checks in tests
#749 
Code quality
automatic tests
=> More improvement

src/main/example/SSLClientExample.java, src/test/java/org/java_websocket/issues/AllIssueTests.java, src/test/java/org/java_websocket/issues/Issue825Test.java
Test to ensure that reconnet works with wss
#825 
Ensure it does not break
Is a test
=> Added test for #825

src/main/java/org/java_websocket/server/WebSocketServer.java
Two minor typo fixes in the WebSocketServer documentation.
=> Fix typos in WebSocketServer

.github/ISSUE_TEMPLATE/bug_report.md, README.markdown, src/main/example/simplelogger.properties
Update all the documentation required for the changes due to logging etc
Fixes #755
Documentation
m
Not needed
=> Update documentation for 1.4.0

src/test/java/org/java_websocket/issues/Issue825Test.java
Use latches instead of timeouts
#877
More stable tests
Locally run
=> Make Issue825Test more stable

build.gradle
Fixes #907 
The issue and solution is described here: https://stackoverflow.com/questions/53709282/cannot-add-task-wrapper-as-a-task-with-that-name-already-exists
`git blame` shows that build.gradle was last modified in 2013: c2e74934 and therefore uses a **very** old version of Gradle (1.4). Since Gradle wrapper isn't currently tracked in the git repo (maybe it should be?), I simply deleted the whole 'wrapper' block.
#907 
The current `build.gradle` file is outdated and produces errors when used with modern Gradle versions.
Building with Gradle 5+ now works as expected.
=> Remove outdated 'wrapper' task from build.gradle (#907)

README.markdown, pom.xml
Update pom and documentation
Fixes #982 
New version
not needed
=> Release of 1.4.1

README.markdown, pom.xml
Release of 1.5.0
Fixes #1005 
Documentation
No test needed
=> Release of 1.5.0

README.markdown, pom.xml
Documentation
#1013 
Documentation
No test needed
=> Release 1.5.1

src/main/java/org/java_websocket/WebSocketImpl.java
=> Added missing return character

build.gradle
Update build.gradle : make it same as pom.xml, include `version`, `groupId`
=> Update build.gradle : make it same as pom.xml

README.markdown, src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java, src/main/java/org/java_websocket/framing/FramedataImpl1.java, src/test/java/org/java_websocket/extensions/PerMessageDeflateExtensionTest.java
=> Update PerMessageDeflateExtension 

src/main/java/org/java_websocket/drafts/Draft_6455.java, src/test/java/org/java_websocket/drafts/Draft_6455Test.java
=> Fix issue #1053 : Adding check conditions - empty value check

src/main/java/org/java_websocket/framing/FramedataImpl1.java, src/test/java/org/java_websocket/framing/CloseFrameTest.java
Fix the failure of the CloseFrameTest.
opcode is mismatched with optcode in the CloseFrameTest #1055
=> [HotFix]Fix the failure of the CloseFrameTest.

.github/workflows/sonar.yml, pom.xml
Add SonarQube action
Improve code qualtity
No test needed, ony CI
=> Add SonarQube Action

build.gradle, pom.xml, src/main/java/org/java_websocket/SSLSocketChannel.java
Documentation
Fixes #1107
Documentation
No test needed
=> Release 1.5.2

.github/workflows/sonar.yml
Do SonarQube only for pushes (silly credentials)
=> Deactivate sonar for pull requests

src/main/example/ExampleClient.java
=> mini comment error

CHANGELOG.md, README.markdown
Changelog and readme
#1228
No test needed
=> Update changelog and readme

build.gradle, pom.xml
=> Update to next version 1.5.4

.github/workflows/checkstyle.yml, .github/workflows/ci.yml, .github/workflows/sonar.yml
See https://github.com/TooTallNate/Java-WebSocket/pull/1309
=> Add distribution attribute to GitHub workflows

pom.xml
Increase to next version 1.5.5 and merge changes required for the release
=> Increase version to 1.5.5

README.markdown
This PR updates the version in the install instructions to match the latest version
Closes #1347
This PR will tell users to install the latest version rather than 1.5.3
This PR does not update code, but I have followed the maven instructions to install version 1.5.4
=> Bump version in install instructions

CHANGELOG.md
=> Update changelog for 1.5.5

build.gradle, pom.xml
=> Increase version to 1.5.6

build.gradle, pom.xml
=> Increase version to 1.5.7

CHANGELOG.md, README.markdown, build.gradle, pom.xml
=> Release 1.5.7

CHANGELOG.md, README.markdown, build.gradle, pom.xml
=> Release 1.6.0

README.markdown
=> Remove outdated build info badge
