TooTallNate/Java-WebSocket

src/main/java/org/java_websocket/SocketChannelIOHelper.java
src/main/java/org/java_websocket/server/WebSocketServer.java

NullPointerException is making the server to crash.  This is also a security breach because an intruder could make your server to crash by simply connecting and start typing random characters. This commit would fix this.

Preventing the server to crash because of a NPE. Issue #224

---

src/main/java/org/java_websocket/server/WebSocketServer.java

The isClosed reference is always to the same instance of AtomicBoolean, hence it should be final rather than volatile.

AtomicBoolean shouldn't be volatile

---

src/main/java/org/java_websocket/client/WebSocketClient.java

My colleague and I noticed that when the handshake request fails (e.g. when the server sends back an HTTP status code of 400), the client hangs. Tracing the code we found that this is because the WebSocket never fully closes.
If the handshake fails, the WebSocket engine's internal state is set to "closing". Presumably the next thing that should happen is the `eot` cleanup. However, this can never be reached because the loop to consume more bytes from the WebSocket only breaks when the client is fully "closed". This change makes sure that the client also does not wait to read more bytes if the client is in the process of shutting down.

Do not decode frames when WebSocket is in "closing" state

---

src/main/java/org/java_websocket/server/WebSocketServer.java

close the selector when the WebSocketServer's selectorthread is finishing. This allows the port to be freed on stop() and another instance to bind on the same port.

Close WebSocketServer's selector to free socket

---

src/main/java/org/java_websocket/drafts/Draft_76.java

Since minimum required JDK for this library is Android 1.6 (API 4), as stated in README.markdown, calls to String.isEmpty() are replaced with String.length() .

Replaced String.isEmpty() with String.length() for Android API level 8 compatibility

---

src/main/java/org/java_websocket/SSLSocketChannel2.java

Fix for #458 (code cleanup of #459)

Fixing 100% CPU untilisation when SSL negotiations fail

---

src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/server/WebSocketServer.java

Make TCP_NODELAY accessible

---

src/main/java/org/java_websocket/WebSocketFactory.java
src/main/java/org/java_websocket/framing/CloseFrame.java
src/main/java/org/java_websocket/framing/CloseFrameBuilder.java
src/main/java/org/java_websocket/framing/FrameBuilder.java
src/main/java/org/java_websocket/framing/Framedata.java
src/main/java/org/java_websocket/framing/FramedataImpl1.java
src/main/java/org/java_websocket/server/DefaultSSLWebSocketServerFactory.java
src/main/java/org/java_websocket/server/DefaultWebSocketServerFactory.java
src/main/java/org/java_websocket/server/WebSocketServer.java

Cleaned up old unused arguments
Added some additional java docs comments

Cleanups & JavaDocs

---

src/main/java/org/java_websocket/server/DefaultSSLWebSocketServerFactory.java

Remove TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 to not cause problems with
firefox

Fix for #466

---

src/main/java/org/java_websocket/client/WebSocketClient.java

Reverts TooTallNate/Java-WebSocket#475

Revert "Fix for #217 by ddrscott"

---

src/main/java/org/java_websocket/AbstractWebSocket.java

Connections dont always get cleaned up after lost connection

---

src/main/java/org/java_websocket/client/WebSocketClient.java

Added internal support for ssl when using wss schema.

Add true WSS support to WebSocketClient

---

src/main/java/org/java_websocket/server/WebSocketServer.java

If an endpoint is not sending a handshake and then closing the
connection, this should not cause an AssertError resulting in a server
shutdown. See #512

Recieving no handshake from the endpoint should not cause a server shutdown

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/drafts/Draft.java
src/main/java/org/java_websocket/drafts/Draft_10.java
src/main/java/org/java_websocket/drafts/Draft_6455.java
src/main/java/org/java_websocket/extensions/CompressionExtension.java
src/main/java/org/java_websocket/extensions/DefaultExtension.java
src/main/java/org/java_websocket/extensions/IExtension.java

Infrastructure for websocket extension

---

src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/drafts/Draft.java
src/main/java/org/java_websocket/drafts/Draft_10.java
src/main/java/org/java_websocket/drafts/Draft_6455.java
src/main/java/org/java_websocket/drafts/Draft_6455_WebRTC.java
src/main/java/org/java_websocket/drafts/Draft_75.java

- Move processing of frames to draft
- Improve handling of IOExceptions causing eot()

Move processing of frames to drafts & improve handling of IOExceptions

---

src/main/java/org/java_websocket/WebSocketImpl.java

This pull request fixes what seems to be a bug. 
If the handshake is refused when establishing connection with server, `flushAndClose()` is called twice, first with `CloseFrame.NEVER_CONNECTED`, then with `CloseFrame.PROTOCOL_ERROR`.

Fix duplicate call of flushAndClose() if status code is PROTOCOL_ERROR on close() method.

---

src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/framing/CloseFrame.java
src/main/java/org/java_websocket/framing/TextFrame.java

Refactoring in WebSocketImpl so the getter/setter for readyState are now used
onClose will not have null as a reason any more for no valid utf8-strings
#577 
Bugfix and code cleanups
Test suite

Refactoring and improved onClose behaviour

---

src/main/example/ChatServer.java
src/main/example/ExampleClient.java
src/main/example/FragmentedFramesExample.java
src/main/example/ServerRejectHandshakeExample.java
src/main/java/org/java_websocket/client/WebSocketClient.java

Removed socket.shutdownOutput due to no implementation in SSLSocket
Small changes to the example classes

Adjusted examples

---

src/main/java/org/java_websocket/client/WebSocketClient.java
src/test/java/org/java_websocket/misc/OpeningHandshakeRejectionTest.java

Also removed assert() in WebSocketClient runnable since it has no
understandable purpose!
Removed assert() in WebSocketClientRunnable
Improved OpeningHandshakeRejection test
Cleanup
Standard JUnit-Tests

Improved OpeningHandshakeRejection test

---

pom.xml
src/main/java/org/java_websocket/WebSocketImpl.java

Added a check when the close frame is send if the connection is still open
#579 
Bug
Against test suite

Check for sending a close frame

---

.gitignore
Jenkinsfile
src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java

Check in the timertask to make sure that a connection is really open.
closeConnection() can also adjust the readystate to closing, if the closecode is CloseFrame.Abnormal_Close and the connection is still open
#606 
#609
#606 caused an exception
#609 just looked messy. But was no real problem due to closeConnection() changing the readystate to closed at the end
Tested against demo project. Waiting for user feedback

 Check if connection is open on sendPing &  change readystate on closeConnection 

---

src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue609.java

Issue was caused due to closeConnection() and eot() do not update the readystate before onWebSocketClose() is called
Fixes #613
Extend test coverage

Test coverage for #609

---

README.markdown
build.xml
src/main/java/org/java_websocket/WebSocketImpl.java
src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue580Test.java
src/test/java/org/java_websocket/issues/Issue621Test.java
src/test/java/org/java_websocket/util/ThreadCheck.java

This is a fix for #621.
It also includes a test for #580, which still fails sometimes (see #620)
We check for the readystate of the connection in the decode() method.
Fixes #621 
Change is required otherwise the caught exception will happen
New Test (Issue621Test)

Fix for #621

---

src/main/java/org/java_websocket/WebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java

This allows a WebSocket connection object to have any kind of data associated.
You can now store information of each connection/user and access it when `onMessage` or `onClose` is fired.
```java
public void onOpen(WebSocket conn, ClientHandshake handshake) {
User user = new User(conn);
conn.setAttachment(user);
}
public void onMessage(WebSocket conn, String message) {
User user = conn.getAttachment();
// ...
}
```
#485 _Create key/value map in WebSocket_
I need to store information about each connection, id, name, etc.
I started by open an issue, then @marci4 replied there was an open discussion about my problem here: #485. After reading all it was said about a possible implementation, I did some performance tests between implementing an `HashMap` or creating a getter and a setter to an …

Added setAttachment and getAttachment to WebSocket interface

---

src/main/java/org/java_websocket/client/AbstractClientProxyChannel.java

Mark AbstractClientProxyChannel as deprecated

Mark AbstractClientProxyChannel as deprecated

---

src/main/java/org/java_websocket/framing/CloseFrame.java
src/test/java/org/java_websocket/autobahn/AutobahnServerResults.java
src/test/java/org/java_websocket/framing/CloseFrameTest.java

Added support for close codes 1012-1014
See https://www.iana.org/assignments/websocket/websocket.xml#close-code-number for reference
Removed autobahn test result check for test 7.9.6 since this testcase will now always fail!
Fixes #639 
Additions to the specification
Adjusted CloseFrame test
Adjusted Autobahn test result check

Support for close code 1012-1014

---

src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/issues/Issue661Test.java

Check if selector is not null
Interrupt for selectorthread to avoid zombie threads
Fixes #661
Bug
Added Issue661Test

NPE on already bound port

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue666Test.java
src/test/java/org/java_websocket/util/ThreadCheck.java

All threads should have a custom name
Also added getConnections() to return an unmodifiable list
Fixes #666 
Clear names and clean up
Issue666Test

 Give all threads a custom name 

---

src/main/java/org/java_websocket/AbstractWebSocket.java

Include reason for DC
Fixes #669 
Documentation
No tests needed.

Include reason for dc due to lost connection detection

---

src/main/java/org/java_websocket/WebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue677Test.java

Deprecate Connecting and additional tests
Fixes #681 
Improve code quality
No tests needed

Deprecate Connecting and additional tests

---

src/main/java/org/java_websocket/WebSocketImpl.java

Removed assertion from WebSocketImpl.isOpen()
Issue #694 
There are some situations where the assertion may be triggered from normal usage.
A getter method such as this should not throw an exception. 
The project builds correctly and examples run. I have not run the autobahn test suite.
I doubt any of the following should apply in this case:

Removed assertion from WebSocketImpl.isOpen (see #694)

---

src/main/java/org/java_websocket/AbstractWebSocket.java

Storing the state of the WebSocket and if setConnectionLostTimeout is used, the timer will be updated
#699
This allows the restart of the detection.
No tests currently needed

Enable and Disable ping/pong

---

src/main/java/org/java_websocket/server/WebSocketServer.java

Added two new methods to WebSocketServer: `broadcast(ByteBuffer)` and `broadcast(ByteBuffer, Collection<WebSocket>`).
Since was duplicated code, I forwarded the `broadcast(byte[])` methods to the ByteBuffer version by using `ByteBuffer.wrap`
#711 
It allows broadcasting data from a ByteBuffer.
All tests are passing.
I haven't added any extra tests, mostly because I have no idea where to put them (where are the old broadcast methods tested?). Whoever reviews this, please answer that.

Added a broadcast method for ByteBuffers

---

src/main/java/org/java_websocket/AbstractWebSocket.java

Catch exceptions !
Fixes #715 
Bugfix
Review

Catch exceptions in AbstractWebSocket

---

src/main/java/org/java_websocket/WebSocketImpl.java

Removes static for the synchronize object
Fixes #726 
Source review

Remove static from synchronize object

---

src/main/java/org/java_websocket/client/WebSocketClient.java
src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue732Test.java

Throw an exception if you are using reconnect in a websocket thread
Fixes #732 
No blocking + info
Added tests

Exception when using reconnect in websocket thread

---

src/main/example/simplelogger.properties
src/main/java/org/java_websocket/SSLSocketChannel.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/drafts/Draft_6455.java
src/main/java/org/java_websocket/exceptions/LimitExedeedException.java
src/test/java/org/java_websocket/drafts/Draft_6455Test.java
src/test/java/org/java_websocket/example/AutobahnServerTest.java
src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue598Test.java

It should be possible to limit the received payload
Fixes #598
If you e.g. know that you only receive should receive 10 bytes, you can force a close of the connection if you receive a bigger limit
Unit-Tests

Implements Memory Management

---

src/test/java/org/java_websocket/issues/Issue765Test.java

Test for #765 
#765 
Test
Added this as a test

Test for 765

---

src/main/java/org/java_websocket/server/WebSocketServer.java

Null the reference to ensure that gc can clean up everything
Fixes #773 
Memory leak
Confirmed by reporter and checked with profiler

Null the reference of the WebSocketImpl

---

src/main/java/org/java_websocket/WebSocketImpl.java

Adding a key word `volatile` to avoid non thread-safe checking of `WebSocketImpl.readyState`.
Checking field WebSocketImpl.readyState is non thread-safe #808

Synchronize the readState field

---

README.markdown

Building with `ant` is no longer supported (de70cdc) but README still contains instructions on how to build with `ant`
#819 
Hopefully obvious
Looks fine to me

Remove outdated build instructions from README

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/test/java/org/java_websocket/issues/Issue811Test.java

Synchronize around the public api related to the lost connection
#811 
Improve thread safety
Added additional unit test

Synchronize AbstractWebSocket

---

src/main/java/org/java_websocket/SocketChannelIOHelper.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/server/WebSocketServerTest.java

Fixed some sonarqube errors & added some tests for the websocket server
#749 
Code quality

Fix some sonarqube errors

---

src/main/example/SSLClientExample.java
src/main/example/TwoWaySSLServerExample.java
src/main/java/org/java_websocket/server/SSLEngineWebSocketServerFactory.java
src/main/java/org/java_websocket/server/SSLParametersWebSocketServerFactory.java
src/test/java/org/java_websocket/server/SSLParametersWebSocketServerFactoryTest.java

Introduces a new class SSLEngineWebSocketServerFactory that takes a SSLEngine as parameter allowing for more customization.
https://github.com/TooTallNate/Java-WebSocket/issues/838
Now I can create a WebSocketServerFactory with a SSLEngine that has NeedClientAuth set to true, thus making Server request a client certificate on connect.
Created a TwoWaySSLServerExample(included in PR) that sets the value. Running wireshark with and without that flag set I can see a difference and the server sending a "client certificate request"

SSLEngineWebSocketServerFactory allows more customization

---

src/main/java/org/java_websocket/client/WebSocketClient.java

In the class WebSocketClient in the close function, I passed the "code" argument on to the "close" call of the WebSocketImpl "engine".
This bug was mentioned in #827.
This fixes a bug where the originally supplied CloseFrame code was ignored and the CloseFrame.NORMAL code was passed on instead.
All the existing unit tests passed. I manually looked at the implementations of the close function and at the usages of the code argument and came to the conclusion that this change shouldn't have introduced a new issue.
This admittedly small amount of testing should suffice since this is only a minor bug fix that utilises existing functions.

Pass on exit code in WebSocketClient close function - fixes bug #827

---

src/test/java/org/java_websocket/exceptions/InvalidEncodingExceptionTest.java

Removed a few imports from InvalidEncodingExceptionTest.
One of those imports was `org.omg.CORBA.DynAnyPackage.Invalid` which comes from a deprecated package and prevents test compilation on JDK 11 (see relevant [JEP](https://openjdk.java.net/jeps/320))
Fixes test compilation on platforms where `org.omg.CORBA.DynAnyPackage.Invalid` is unavailable, such as JDK 11 and later
No functionality has been modified, the imports were not used (I'm assuming they're a result of an accidental IDE auto-import)

Removed unused/unrelated imports (including deprecated CORBA)

---

CHANGELOG.md

Generated changelog.md
Fixes #845 
Documentation
No test needed

Generated changelog

---

src/main/java/org/java_websocket/drafts/Draft_6455.java
src/test/java/org/java_websocket/issues/Issue847Test.java
src/test/java/org/java_websocket/util/KeyUtils.java

This PR fixes the issue introduced with #805 
Fixes #847 
Bug fix
Added a new test

Fix issue #847

---

src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/issues/AllIssueTests.java
src/test/java/org/java_websocket/issues/Issue834Test.java

I changed the constructor of the `WebSocketServer` class to only instantiate the `WebSocketWorkers` but not start them. Now they are started in a foreach loop in the start function.
This fixes the issue #834.
Now the `WebSocketWorkers` are only started when the `WebSocketServer` is started instead of when it was instantiated. These `WebSocketWorkers` run in different threads and would keep the program alive even though the `WebSocketServer` was not running but simply instantiated.
All JUnit tests passed and the gist in the issue now properly terminates since the worker threads are never started. I did not see the need for an additional JUnit test for this small fix but would happily provide one if desired.

Fix issue #834 by starting WebSocketWorker of the WebSocketServer in the start function

---

src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/issues/Issue855Test.java

Move the startup of the WebSocketWorker inside of the run() method
Fixes #855
Bug found in regression test
Additional test

Move the startup of the WebSocketWorker inside of run() 

---

CHANGELOG.md
README.markdown
build.gradle
pom.xml

New version!
#854 
Update documentation and version
Not needed

Release of 1.4.0

---

src/main/java/org/java_websocket/client/WebSocketClient.java

Added a way to add headers in the handshake before connecting/reconnecting. Also added a method to delete a header, and to clear all headers.
Related to issue #865.
New Feature

Add a way to put additional headers to handshake for connecting/reconnecting, see #865

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/util/NamedThreadFactory.java
src/test/java/org/java_websocket/issues/Issue666Test.java

By getting rid of TimerTask, we remove an assumption that the system clock will not be modified.
Fixes #869 
Observed that there is no longer an issue when the system time is changed.

Replace TimerTask with ScheduledExecutorService

---

src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/issues/Issue879Test.java

It is possible to have get a ConcurrentModificationException when using broadcast and a new client connects/drops
Found with #879
Bugfix
Developed test

ConcurrentModificationException when using broadcast

---

src/main/java/org/java_websocket/SSLSocketChannel.java
src/main/java/org/java_websocket/SSLSocketChannel2.java
src/main/java/org/java_websocket/WebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/interfaces/ISSLChannel.java
src/main/java/org/java_websocket/interfaces/package-info.java
src/test/java/org/java_websocket/issues/Issue825Test.java
src/test/java/org/java_websocket/issues/Issue890Test.java
src/test/java/org/java_websocket/util/SSLContextUtil.java

There is currently no good way to access the SSLSession used for a websocket.
Therefore it is not possible to examine client certificates
Fixes #890
Clean methods to access the SSLSession.
Manual test

 Provide a way to access the SSLSession of a websocket instance 

---

README.markdown

The actual link for getting information about wss on android is broken, so I'm updating it with a link from the relevant page in the wiki.
This comes to solve the #924 issue.
I'm fixing a link the project's README in order to help who may need information about SSL support on android.
No tests required.

Fix broken link on README.markdown

---

src/test/java/org/java_websocket/util/Base64Test.java
src/test/java/org/java_websocket/util/CharsetfunctionsTest.java

Hi,
I've analysed your code base and noticed that `org.java_websocket.util.Base64` and `org.java_websocket.util.Charsetfunctions` are not fully tested.
I've written some tests that cover these classes with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

Add unit tests for Base64 and Charsetfunctions

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/SSLSocketChannel.java
src/main/java/org/java_websocket/SSLSocketChannel2.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/drafts/Draft_6455.java
src/main/java/org/java_websocket/server/WebSocketServer.java

The slf4j Loggers were changed to be declared as non-static.
The slf4j Loggers were declared as `private static final`. This has been changed to `private final`.
Fixes #969.
Usage of `private static final` loggers (or other classes in general) can be problematic it environments with shared classpaths and dynamic loading/unloading of JARs.
For reference see:
http://slf4j.org/faq.html#declared_static
https://cwiki.apache.org/confluence/display/COMMONS/Logging+StaticLog
No functional changes were introduced by this change.
(There were some failing tests before this change. The same ones are still failing.)

Made loggers non-static to support deployment in containers

---

pom.xml

Changed `pom.xml` so that the OSGi metadata is created and included in the resulting JAR.
Added the `bnd-maven-plugin` and its configuration to the `pom.xml` so that resulting JAR will contain OSGi metadata.
Fixes #822 .
Enables usage of the library in OSGi without the requiring the user to wrap the library.
The library JAR still gets created.
(The same failing tests as before the change are still failing afterwards...)

Enabled OSGi metadata in MANIFST-MF for created JAR

---

src/main/java/org/java_websocket/server/WebSocketServer.java

~~Theoretically I should add this to 1.5.0 milestone, but since this is a non-breaking change and we also have a non-breaking #1000, so maybe there should be a small 1.4.2 release so that people can use these improvements without breaking changes of 1.5.0? I will add the appropriate @​since tags to JavaDoc when this is decided.~~
Adds a field and two new methods to WebSocketServer: `setMaxPendingConnections(int)` and `getMaxPendingConnections()` and uses the value as a parameter when binding the server socket.
Fixes #991
This change allows users to configure the maximum number of pending connections.
Existing tests run fine.

Allow user to specify max number of pending connections to a server

---

src/main/java/org/java_websocket/client/WebSocketClient.java
src/test/java/org/java_websocket/issues/Issue997Test.java

Hotfix for 1.5.0
#Fixes 1011
Workaround for Android users
Workaround is documented in our wiki (https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-'setEndpointIdentificationAlgorithm')
Review

Move setEndpointIdentificationAlgorithm inside onSetSSLParametersof

---

src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/test/java/org/java_websocket/client/AllClientTests.java
src/test/java/org/java_websocket/client/SchemaCheckTest.java

Enforce Use appropriate schema in any case
throw exception if use invalid schema in websocket client.
Fixes #1026 
I think we should force users to use valid schema. Avoid confusion when using the invalid schema without throwing an exception

Use appropriate schema in any case

---

src/main/example/ChatServer.java
src/main/example/SecWebSocketProtocolServerExample.java
src/main/java/org/java_websocket/WebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/protocols/Protocol.java
src/test/java/org/java_websocket/drafts/Draft_6455Test.java
src/test/java/org/java_websocket/protocols/ProtoclHandshakeRejectionTest.java
src/test/java/org/java_websocket/protocols/ProtocolTest.java

Make protocol less strict
Fixes #1008 
Reduce frustration
New tests

Make Sec-WebSocket-Protocol less strict

---

src/test/java/org/java_websocket/issues/Issue256Test.java

Fix the failure of issue256Test.
Why `issue256Test` would always fail when we run the first test?
It is because we got the incompletes current thread in the method `ThreadCheck.before()`, when it went too fast so that the server's workers were not all started.
After the first test, we could got the completes current thread in the next tests because at the time the server was ready and all its workers were started. Thus, the next tests would success.

Fix the failure of Issue256Test.

---

src/main/java/org/java_websocket/client/WebSocketClient.java

Use the provided socket factory over a newly created one when creating a socket with a proxy
Fixes #1058
Bug fix
Manual test. Contains NO automatic test

Prioritise using provided socket factory when creating socket with proxy

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/drafts/Draft_6455.java
src/main/java/org/java_websocket/exceptions/LimitExceededException.java
src/main/java/org/java_websocket/exceptions/WrappedIOException.java
src/main/java/org/java_websocket/extensions/ExtensionRequestData.java
src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java
src/main/java/org/java_websocket/handshake/HandshakedataImpl1.java
src/main/java/org/java_websocket/server/DefaultSSLWebSocketServerFactory.java
src/main/java/org/java_websocket/server/WebSocketServer.java
src/test/java/org/java_websocket/protocols/AllProtocolTests.java
src/test/java/org/java_websocket/protocols/ProtocolHandshakeRejectionTest.java
src/test/java/org/java_websocket/server/AllServerTests.java
src/test/java/org/java_websocket/server/WebSocketServerTest.java

This PR fixes issues found by SonarQube
Ongoing move to improve code quality
Automatic tests

Improve code quality

---

src/main/java/org/java_websocket/WebSocket.java

Update documentation comments for methods getRemoteSocketAddress and getLocalSocketAddress in WebSocket.java.
Fixes #1108
Fixes documentation issue mentioned in the related issue.

WebSocket.java documentation comments update

---

src/main/java/org/java_websocket/drafts/Draft_6455.java

Fixes #1132
Connect to a remote server.

Use SecureRandom instead of Random

---

build.gradle

* Bump javac to 1.7 to match pom.xml
* Use new plugin block syntax
* Replace deprecated 'maven' plugin with 'maven-publish' (as described here: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins)
* replace deprecated 'compile' and 'testCompile' configurations with 'implementation' and 'testImplementation', respectively. (**Note: this assumes that slf4j is an internal dependency and it's API is not exposed to users of this library**)
Ensures that this project can be built using Gradle
Built on jdk-8 and jdk-15, with Gradle 6.8.3. I manually verified that the maven-publish plugin works and produces the following POM file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project …
```

Gradle build update

---

src/main/java/org/java_websocket/client/WebSocketClient.java
src/test/java/org/java_websocket/issues/Issue1142Test.java

Added SSLSession API with #890.
This was mainly added for the WebSocketServer. Make it also available in the client.
Fixes #1142
Bugfix
Local test

Provide SSLSession in WebSocketClient

---

src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java
src/test/java/org/java_websocket/example/AutobahnServerTest.java
src/test/java/org/java_websocket/extensions/PerMessageDeflateExtensionTest.java

PerMessageDeflate messages may be uncompressed and should therefore not fail
Fixes #1164
Bugfix
Manual test was not possible since the reporter did not include an example application

PermessageDeflate should handle uncompressed messages

---

src/test/java/org/java_websocket/issues/Issue677Test.java

* This PR fixes a flaky test to avoid an assertion on an asynchronous operation  `org.java_websocket.issues.Issue677Test#testIssue`
* The test fails non-deterministically when execution delays occur. To observe a test failure, the unmodified test can be re-executed many times. the likelihood of observing a test failure increases when the test executes on a slow machine. To deterministically reproduce the test failure, introduce an execution delay:
```java
@Test
public void testIssue() throws Exception {
...
server.start();
countServerDownLatch.await();
webSocket0.connectBlocking();
assertTrue( "webSocket.isOpen()", webSocket0.isOpen() );
webSocket0.close();
Thread.sleep(20);
assertTrue( "webSocket.isClosing()", webSocket0.isClosing() ); //fail
...
}
```
* The test should run successfully …

Removing assertion in asynchronous operation to avoid flaky test

---

src/main/java/org/java_websocket/WebSocketImpl.java
src/test/java/org/java_websocket/issues/Issue1203Test.java

Reset the lastPong in onOpen
Fixes #1203
Bug
Automatic test

Reset lastPong in onOpen

---

src/main/java/org/java_websocket/SSLSocketChannel2.java

There can be IOException when trying to close channel. That create infinitive loop.
#459 #458 
Tested on my production one week. Standart connection count from 500 up to 2k

high cpu when channel close exception fix

---

.idea/.gitignore
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/server/WebSocketServer.java

Added java.lang.Error handling in WebSocketImpl and WebSocketServer. Fatal Error ( VirtualMachineError | ThreadDeath | LinkageError ) lead to stopping of WebSocketServer. Now non-fatal Error leads to closing of web socket but not stopping of WebSocketServer.
Fixes #1160

Issue-1160 Added java.lang.Error handling in WebSocketImpl and WebSocketServer

---

src/main/java/org/java_websocket/server/WebSocketServer.java

Correct web socket closing in case if Server caught error

Correct web socket closing

---

src/main/java/org/java_websocket/drafts/Draft_6455.java
src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java

Fixes #1230 
Autobahn testsuite

Adjust the handling of RSV1/RSV2/RSV3 in the translateSingleFrame

---

src/main/java/org/java_websocket/drafts/Draft.java
src/test/java/org/java_websocket/example/AutobahnClientTest.java
src/test/java/org/java_websocket/example/AutobahnSSLServerTest.java
src/test/java/org/java_websocket/example/AutobahnServerTest.java

Replace usages of deprecated constructor Integer(String) with Integer.parseInt
https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#Integer-java.lang.String-
> @Deprecated(since="9")
> public Integer​(String s)
>  &nbsp; &nbsp; &nbsp;throws NumberFormatException
> Deprecated. It is rarely appropriate to use this constructor. Use [parseInt(String)](https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#parseInt-java.lang.String-) to convert a string to a int primitive, or use [valueOf(String)](https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#valueOf-java.lang.String-) to convert a string to an Integer object.
> 
Tests work same as before

Replace usages of deprecated constructor Integer(String) with Integer.parseInt

---

src/main/java/org/java_websocket/WebSocketImpl.java

avoid string copy in web socket frame decoding
before decoding frames, the implementation logs the first 1000 char from the socket buffer. a string object is created even if log is disabled.
changes: check the logging level before creating the logging parameters
[x] minor improvement

websocketimpl: avoid string copy unless logging trace message

---

src/test/java/org/java_websocket/util/Base64Test.java

Base64Test fails on JDK 16+ due to https://bugs.openjdk.org/browse/JDK-8253142
#1306 
To allow building the project with recent JDKs
Running the tests

Make Base64Test independent of JDK

---

.github/workflows/checkstyle.yml
.github/workflows/ci.yml
.github/workflows/sonar.yml
pom.xml
src/main/java9/module-info.java

Add support for Java modules. The slf4j-api dependency was also updated to use a modularized version.
#1308
It allows projects that depend on this project to be modularized as well. And it allows encapsulating packages (such as the `utils` package).
Building the project and verifying that the created JAR is now modular with `jar -d -f .\Java-WebSocket-1.5.4-SNAPSHOT.jar --release 9`

Add support for Java modules

---

build.gradle

#1370 
There is inconsitent versions of slf4j dependencies between maven and gradle.

Align slf4j version between maven and gradle.

---

src/main/java/org/java_websocket/client/WebSocketClient.java

This fixes some issues regarding reconnect. 
Previously there was a massive thread leak caused by repeatedly reconnecting, this no longer happens (tested manually with VisualVM profiler). Also race conditions with null pointer exceptions in multiple places.
No exceptions, leaked threads, deadlocks or other problems found after running 100000 iterations of reconnecting with various delays inbetween. No *new* test failures (I think one existing failure might be fixed but not sure yet)
To be honest this code is a multithreading nightmare but the general idea of this PR is to make sure that there may exist only one read/write thread per WebSocketClient and it can never be leaked due to "interrupt+join" combination before each reassignment.
I have also removed some unneeded assignments to null …

Fix multiple issues related to reconnect

---

src/main/java/org/java_websocket/WebSocketAdapter.java
src/main/java/org/java_websocket/WebSocketListener.java
src/main/java/org/java_websocket/server/WebSocketServer.java
src/main/java/org/java_websocket/util/Base64.java

HTML5 has dropped the `<tt>` tag and new versions of the `javadoc` will refuse to generate such docs:
```
Java-WebSocket/src/main/java/org/java_websocket/server/WebSocketServer.java:922: error: tag not supported in HTML5: tt
* @param conn    The <tt>WebSocket</tt> instance this event is occurring on.
```
Generating javadocs works and output is formatted as expected

Replace <tt> with <code> in javadocs

---

src/main/java/org/java_websocket/client/WebSocketClient.java

Without further configuration TLS v1.2 is enforced when connecting to a server. Thus a connection to a server supporting TLS 1.3 only is refused. Recent JREs use TLS v1.2 and TLS v1.3 as the default value, which can be further adjusted via  _jdk.tls.client.protocols_ property.
Fixes #1382
Allows to configure TLS versions via a global property: jdk.tls.client.protocols
- 12 of 721 tests failed. No idea what the cause is. The number is however the same for both master and my branch.

Retrieve default SSL socket factory

---

CHANGELOG.md
README.markdown
build.gradle
pom.xml

Release 1.5.6

---

src/main/java/org/java_websocket/client/WebSocketClient.java

Fixes #1397
Previously, `connectBlocking(long, TimeUnit)` would return a boolean indicating whether the connection was set up in the given window. If false was returned, we would continue to attempt connecting in the background. This PR updates `connectBlocking(long, TimeUnit)` to perform cleanup on timeout.
- Unit tests have been run
- See "To Reproduce" steps on https://github.com/TooTallNate/Java-WebSocket/issues/1397 - I used the firewall rules listed, and then updated the sample app linked to run the default client in a in a loop (500 iterations) to verify there were no thread or memory leaks
Note: I spent a couple hours spiking a unit test around this change but couldn't come up with anything solid. I found it difficult to simulate the "drop packets mid-connection" firewall rule …

Have connectBlocking clean up after a timeout

---

src/main/java/org/java_websocket/AbstractWebSocket.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/server/WebSocketServer.java

Add new setter/getter which controls the TCP receive buffer size (previously hardcoded as 16K)
This is intended to solve #1406 in a more general way
Before merging this I would like to manually verify that setting the buffer size affects performance as expected

Allow setting custom TCP receive buffer size

---

src/test/java/org/java_websocket/client/ConnectBlockingTest.java

Originally I wanted to simulate a real network interruption via TCP proxy, but I don't see any case where it would act differently to just ignoring the socket completely. As expected, the test fails on previous versions, without the fix in #1399

Add test for connectBlocking cleanup (#1399)

---

src/main/java/org/java_websocket/SSLSocketChannel2.java

On Ubuntu 22.04 with Linux 6.5, it was observed that when the server gets the SSL records containing the client handshake finished message and the first HTTP GET request in ONE read operation, the latter SSL record is never processed.
Commit 89eaf410dd8fe3845fa6fb0de3469b55da0205cb should have fixed this, but it turned out that when SSLSocketChannel2#processHandshake() is called from SSLSocketChannel2#write(), the second SSL record containing the HTTP GET request is stashed away, but never retrieved, since the calling code in WebSocketServer#doWrite() has no provisions for this, only WebSocketServer#doRead() does.
Change SSLSocketChannel2#processHandshake() to only read from the socket when called from SSLSocketChannel#read(), to ensure that when two SSL records are read, the second one …

Fix issue #1418: WebSocketServer sometimes misses GET request after SSL handshake

---

src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java
src/test/java/org/java_websocket/extensions/PerMessageDeflateExtensionTest.java

Fixes #1437
Fixes #1400
Issue
Additional tests

Clone PerMessageDeflateExtension values correctly

---

src/main/example/SocketActivation.java
src/main/example/jws-activation.service
src/main/example/jws-activation.socket
src/main/java/org/java_websocket/server/WebSocketServer.java

Add support for socket  activation
Added new constructor to WebSocketServer which takes an already prepared Channel.
If this constructor is used, then WebSocketServer will not try to open it's own channel, or bind it since it is expected to be handled by user.
This allows to use System.inheritedChannel() together with systemd socket activation, which passes the prepared socket as file descriptor #0.
Also added an example "smart" chat server, which will be brought up and down on-demand by systemd.
I have tested it and it is working as expected.
TODO: a unit test should be added which creates server with an existing Channel.
I am also considering adding a script for running an integration test in a container, to make sure socket activation works as expected with this feature.
Fixes #1440 …

Socket activation

---

build.gradle

1. Use the API Maven spec instead of the BOM
2. Specify to use the JUnit Platform instead for the `test` task
#1457

Fix JUnit 5 config for gradle
